# Generated by Django 5.2.6 on 2025-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.TextField(
                blank=True, help_text="List of team members, one per line"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="members_info",
            field=models.TextField(
                blank=True,
                help_text="Additional information about team members in format: Student - leader, university, year of study",
            ),
        ),
    ]
