# Generated by Django 5.2.6 on 2025-10-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judging", "0002_team_members_team_members_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="score",
        ),
        migrations.AddField(
            model_name="criteria",
            name="points",
            field=models.FloatField(
                default=0, help_text="Points awarded when this criterion is checked"
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A – Mobile App"),
                    ("B", "B – Web App"),
                    ("C", "C – Telegram Bot"),
                ],
                help_text="Service vector this criteria applies to (for bonus criteria)",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="type",
            field=models.CharField(
                choices=[("main", "Main Criteria"), ("bonus", "Bonus Criteria")],
                default="main",
                help_text="Type of criteria (main or bonus)",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="checked",
            field=models.BooleanField(
                default=False, help_text="Whether this criterion is checked"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A – Mobile App"),
                    ("B", "B – Web App"),
                    ("C", "C – Telegram Bot"),
                ],
                help_text="Service vector for the team",
                max_length=1,
                null=True,
            ),
        ),
    ]
