# Generated by Django 5.2.6 on 2025-10-20 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "judging",
            "0003_remove_score_score_criteria_points_criteria_service_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="max_score",
            field=models.FloatField(
                default=10, help_text="Maximum possible score for this criterion"
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="value",
            field=models.FloatField(
                default=0,
                help_text="Score value (0 to max_score)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="criteria",
            name="points",
            field=models.FloatField(
                default=0,
                help_text="Legacy field - Points awarded when this criterion is checked",
            ),
        ),
        migrations.AlterField(
            model_name="criteria",
            name="type",
            field=models.CharField(
                choices=[
                    ("main", "Main Criteria"),
                    ("bonus_a", "Bonus Criteria for Vector A"),
                    ("bonus_b", "Bonus Criteria for Vector B"),
                    ("bonus_c", "Bonus Criteria for Vector C"),
                ],
                default="main",
                help_text="Type of criteria (main or bonus)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="checked",
            field=models.BooleanField(
                default=False,
                help_text="Legacy field - Whether this criterion is checked",
            ),
        ),
    ]
